-- این Migration صف ارسال همگانی مستقل هر Bot را ایجاد می‌کند.
-- Snapshot گیرنده‌ها باعث می‌شود قطع برنامه یا Retry باعث ارسال تکراری به کاربران قبلی نشود.

-- رکورد اصلی هر ارسال همگانی، متن و آمار پردازش را نگه می‌دارد.
create table if not exists public.botstore_broadcasts (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  message_text text not null check (char_length(message_text) between 1 and 4000),
  status text not null default 'queued' check (status in ('queued','sending','completed','partial','failed')),
  total_recipient_count integer not null default 0 check (total_recipient_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

-- هر گیرنده دقیقاً یک بار در Snapshot همان Broadcast ثبت می‌شود.
create table if not exists public.botstore_broadcast_recipients (
  id bigint generated by default as identity primary key,
  broadcast_id bigint not null references public.botstore_broadcasts(id) on delete cascade,
  customer_id bigint references public.botstore_customers(id) on delete set null,
  telegram_user_id bigint not null,
  status text not null default 'pending' check (status in ('pending','sent','failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error text not null default '' check (char_length(last_error) <= 500),
  attempted_at timestamptz,
  unique (broadcast_id, telegram_user_id)
);

-- تاریخچه هر Bot بر اساس زمان ایجاد سریع خوانده می‌شود.
create index if not exists botstore_broadcasts_bot_created_idx
  on public.botstore_broadcasts(bot_id, created_at desc);

-- Worker اولین گیرنده‌های pending هر Broadcast را سریع پیدا می‌کند.
create index if not exists botstore_broadcast_recipients_pending_idx
  on public.botstore_broadcast_recipients(broadcast_id, status, id);

-- FK مشتری Index جداگانه دارد تا عملیات حذف/بررسی رابطه کند نشود.
create index if not exists botstore_broadcast_recipients_customer_idx
  on public.botstore_broadcast_recipients(customer_id);

-- Data API عمومی به هیچ‌کدام از جدول‌های صف دسترسی مستقیم ندارد.
alter table public.botstore_broadcasts enable row level security;
alter table public.botstore_broadcast_recipients enable row level security;
revoke all on table public.botstore_broadcasts from anon, authenticated;
revoke all on table public.botstore_broadcast_recipients from anon, authenticated;

-- فقط Backend server-side اجازه مدیریت صف را دارد.
grant select, insert, update, delete on table public.botstore_broadcasts to service_role;
grant select, insert, update, delete on table public.botstore_broadcast_recipients to service_role;
grant usage, select on all sequences in schema public to service_role;
