-- این Migration جداول اختصاصی Backend چندرباته App BotStore را ایجاد می‌کند.
-- اجرای مجدد آن امن است چون تمام CREATEها به‌صورت IF NOT EXISTS نوشته شده‌اند.

-- جدول اصلی Botها شناسه Telegram، Token، نام و Secret اختصاصی Webhook را نگه می‌دارد.
create table if not exists public.botstore_bots (
  id bigint generated by default as identity primary key,
  telegram_bot_id bigint not null unique,
  bot_token text not null unique,
  username text not null default '',
  first_name text not null default '',
  webhook_secret text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- هر دسته‌بندی به یک Bot مشخص تعلق دارد و با حذف Bot پاک می‌شود.
create table if not exists public.botstore_categories (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  title text not null,
  emoji text not null default '🛍️',
  position integer not null default 0,
  created_at timestamptz not null default now(),
  unique (bot_id, title)
);

-- محصولات فروشگاه به Bot و در صورت وجود به Category همان Bot متصل می‌شوند.
create table if not exists public.botstore_products (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  category_id bigint references public.botstore_categories(id) on delete set null,
  title text not null,
  price bigint not null default 0 check (price >= 0),
  description text not null default '',
  active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

-- Indexهای مسیرهای اصلی Webhook و Catalog برای مقیاس چندرباته تعریف می‌شوند.
create index if not exists botstore_categories_bot_id_idx
  on public.botstore_categories(bot_id, position, id);
create index if not exists botstore_products_bot_id_idx
  on public.botstore_products(bot_id, active, position, id);
create index if not exists botstore_products_category_id_idx
  on public.botstore_products(category_id, active, position, id);

-- RLS فعال می‌شود ولی Policy عمومی تعریف نمی‌شود؛ این تصمیم عمدی است.
-- anon و authenticated هیچ مجوز مستقیمی ندارند و فقط Backend دارای service_role به این جداول دسترسی دارد.
alter table public.botstore_bots enable row level security;
alter table public.botstore_categories enable row level security;
alter table public.botstore_products enable row level security;

-- دسترسی مستقیم Data API از نقش‌های سمت Client حذف می‌شود.
revoke all on table public.botstore_bots from anon, authenticated;
revoke all on table public.botstore_categories from anon, authenticated;
revoke all on table public.botstore_products from anon, authenticated;

-- Edge Functionهای Backend با service_role عملیات CRUD را انجام می‌دهند.
grant select, insert, update, delete on table public.botstore_bots to service_role;
grant select, insert, update, delete on table public.botstore_categories to service_role;
grant select, insert, update, delete on table public.botstore_products to service_role;

-- دسترسی sequence برای شناسه‌های identity به service_role داده می‌شود.
grant usage, select on all sequences in schema public to service_role;
