-- این Migration هسته مشتری، سبد خرید و سفارش App BotStore را ایجاد می‌کند.

create table if not exists public.botstore_customers (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  telegram_user_id bigint not null,
  first_name text not null default '',
  username text not null default '',
  blocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bot_id, telegram_user_id)
);

create table if not exists public.botstore_cart_items (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  telegram_user_id bigint not null,
  product_id bigint not null references public.botstore_products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0 and quantity <= 999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bot_id, telegram_user_id, product_id)
);

create table if not exists public.botstore_orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  bot_id bigint not null references public.botstore_bots(id) on delete cascade,
  customer_id bigint references public.botstore_customers(id) on delete set null,
  telegram_user_id bigint not null,
  status text not null default 'new' check (status in ('new','awaiting_payment','paid','processing','shipped','completed','cancelled')),
  total_price bigint not null default 0 check (total_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- اقلام سفارش نام و قیمت را Snapshot می‌کنند تا ویرایش یا حذف محصول تاریخچه سفارش را تغییر ندهد.
create table if not exists public.botstore_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.botstore_orders(id) on delete cascade,
  product_id bigint references public.botstore_products(id) on delete set null,
  title_snapshot text not null,
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0 and quantity <= 999),
  line_total bigint not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists botstore_customers_bot_blocked_idx
  on public.botstore_customers(bot_id, blocked, id);
create index if not exists botstore_orders_bot_user_created_idx
  on public.botstore_orders(bot_id, telegram_user_id, created_at desc);
create index if not exists botstore_orders_bot_status_created_idx
  on public.botstore_orders(bot_id, status, created_at desc);
create index if not exists botstore_order_items_order_idx
  on public.botstore_order_items(order_id, id);

alter table public.botstore_customers enable row level security;
alter table public.botstore_cart_items enable row level security;
alter table public.botstore_orders enable row level security;
alter table public.botstore_order_items enable row level security;

-- Clientها به این جداول دسترسی مستقیم ندارند؛ فقط Backend server-side مجاز است.
revoke all on table public.botstore_customers from anon, authenticated;
revoke all on table public.botstore_cart_items from anon, authenticated;
revoke all on table public.botstore_orders from anon, authenticated;
revoke all on table public.botstore_order_items from anon, authenticated;

grant select, insert, update, delete on table public.botstore_customers to service_role;
grant select, insert, update, delete on table public.botstore_cart_items to service_role;
grant select, insert, update, delete on table public.botstore_orders to service_role;
grant select, insert, update, delete on table public.botstore_order_items to service_role;
grant usage, select on all sequences in schema public to service_role;
